// <auto-generated />
using System;
using ContractService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContractService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ContractDbContext))]
    [Migration("20260914011456_InitialCreateContracts")]
    partial class InitialCreateContracts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContractService.Domain.Contracts.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ContractedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("contracted_at_utc");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposal_id");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("ProposalId")
                        .IsUnique()
                        .HasDatabaseName("ux_contracts_proposal_id");

                    b.ToTable("contracts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
